// Code generated by entc, DO NOT EDIT.

package service

const (
	// Label holds the string label denoting the service type in the database.
	Label = "service"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUID holds the string denoting the uid field in the database.
	FieldUID = "uid"
	// FieldHeadcode holds the string denoting the headcode field in the database.
	FieldHeadcode = "headcode"
	// Table holds the table name of the service in the database.
	Table = "services"
)

// Columns holds all SQL columns for service fields.
var Columns = []string{
	FieldID,
	FieldUID,
	FieldHeadcode,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUID holds the default value on creation for the "uid" field.
	DefaultUID string
	// DefaultHeadcode holds the default value on creation for the "headcode" field.
	DefaultHeadcode string
)
