// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CallingPointsColumns holds the columns for the "calling_points" table.
	CallingPointsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "arrival_time", Type: field.TypeTime},
		{Name: "departure_time", Type: field.TypeTime},
	}
	// CallingPointsTable holds the schema information for the "calling_points" table.
	CallingPointsTable = &schema.Table{
		Name:       "calling_points",
		Columns:    CallingPointsColumns,
		PrimaryKey: []*schema.Column{CallingPointsColumns[0]},
	}
	// DaysColumns holds the columns for the "days" table.
	DaysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "date", Type: field.TypeTime},
	}
	// DaysTable holds the schema information for the "days" table.
	DaysTable = &schema.Table{
		Name:       "days",
		Columns:    DaysColumns,
		PrimaryKey: []*schema.Column{DaysColumns[0]},
	}
	// PlatformsColumns holds the columns for the "platforms" table.
	PlatformsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Default: "-"},
	}
	// PlatformsTable holds the schema information for the "platforms" table.
	PlatformsTable = &schema.Table{
		Name:       "platforms",
		Columns:    PlatformsColumns,
		PrimaryKey: []*schema.Column{PlatformsColumns[0]},
	}
	// ServicesColumns holds the columns for the "services" table.
	ServicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uid", Type: field.TypeString, Default: "<00000>"},
		{Name: "headcode", Type: field.TypeString, Default: "0Z00"},
	}
	// ServicesTable holds the schema information for the "services" table.
	ServicesTable = &schema.Table{
		Name:       "services",
		Columns:    ServicesColumns,
		PrimaryKey: []*schema.Column{ServicesColumns[0]},
	}
	// StationsColumns holds the columns for the "stations" table.
	StationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Default: "???"},
		{Name: "crs", Type: field.TypeString, Default: "ZZZ"},
	}
	// StationsTable holds the schema information for the "stations" table.
	StationsTable = &schema.Table{
		Name:       "stations",
		Columns:    StationsColumns,
		PrimaryKey: []*schema.Column{StationsColumns[0]},
	}
	// ToCsColumns holds the columns for the "to_cs" table.
	ToCsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Default: "???"},
	}
	// ToCsTable holds the schema information for the "to_cs" table.
	ToCsTable = &schema.Table{
		Name:       "to_cs",
		Columns:    ToCsColumns,
		PrimaryKey: []*schema.Column{ToCsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CallingPointsTable,
		DaysTable,
		PlatformsTable,
		ServicesTable,
		StationsTable,
		ToCsTable,
	}
)

func init() {
}
