// Code generated by entc, DO NOT EDIT.

package entities

import (
	"context"
	"errors"
	"fmt"
	"time"

	"bitbucket.org/sea_wolf/departure_board-go/v2/entities/callingpoint"
	"bitbucket.org/sea_wolf/departure_board-go/v2/entities/platform"
	"bitbucket.org/sea_wolf/departure_board-go/v2/entities/predicate"
	"bitbucket.org/sea_wolf/departure_board-go/v2/entities/service"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CallingPointUpdate is the builder for updating CallingPoint entities.
type CallingPointUpdate struct {
	config
	hooks    []Hook
	mutation *CallingPointMutation
}

// Where appends a list predicates to the CallingPointUpdate builder.
func (cpu *CallingPointUpdate) Where(ps ...predicate.CallingPoint) *CallingPointUpdate {
	cpu.mutation.Where(ps...)
	return cpu
}

// SetArrivalTime sets the "arrival_time" field.
func (cpu *CallingPointUpdate) SetArrivalTime(t time.Time) *CallingPointUpdate {
	cpu.mutation.SetArrivalTime(t)
	return cpu
}

// SetNillableArrivalTime sets the "arrival_time" field if the given value is not nil.
func (cpu *CallingPointUpdate) SetNillableArrivalTime(t *time.Time) *CallingPointUpdate {
	if t != nil {
		cpu.SetArrivalTime(*t)
	}
	return cpu
}

// SetDepartureTime sets the "departure_time" field.
func (cpu *CallingPointUpdate) SetDepartureTime(t time.Time) *CallingPointUpdate {
	cpu.mutation.SetDepartureTime(t)
	return cpu
}

// SetNillableDepartureTime sets the "departure_time" field if the given value is not nil.
func (cpu *CallingPointUpdate) SetNillableDepartureTime(t *time.Time) *CallingPointUpdate {
	if t != nil {
		cpu.SetDepartureTime(*t)
	}
	return cpu
}

// SetPlatformID sets the "platform" edge to the Platform entity by ID.
func (cpu *CallingPointUpdate) SetPlatformID(id int) *CallingPointUpdate {
	cpu.mutation.SetPlatformID(id)
	return cpu
}

// SetNillablePlatformID sets the "platform" edge to the Platform entity by ID if the given value is not nil.
func (cpu *CallingPointUpdate) SetNillablePlatformID(id *int) *CallingPointUpdate {
	if id != nil {
		cpu = cpu.SetPlatformID(*id)
	}
	return cpu
}

// SetPlatform sets the "platform" edge to the Platform entity.
func (cpu *CallingPointUpdate) SetPlatform(p *Platform) *CallingPointUpdate {
	return cpu.SetPlatformID(p.ID)
}

// SetServiceID sets the "service" edge to the Service entity by ID.
func (cpu *CallingPointUpdate) SetServiceID(id int) *CallingPointUpdate {
	cpu.mutation.SetServiceID(id)
	return cpu
}

// SetNillableServiceID sets the "service" edge to the Service entity by ID if the given value is not nil.
func (cpu *CallingPointUpdate) SetNillableServiceID(id *int) *CallingPointUpdate {
	if id != nil {
		cpu = cpu.SetServiceID(*id)
	}
	return cpu
}

// SetService sets the "service" edge to the Service entity.
func (cpu *CallingPointUpdate) SetService(s *Service) *CallingPointUpdate {
	return cpu.SetServiceID(s.ID)
}

// Mutation returns the CallingPointMutation object of the builder.
func (cpu *CallingPointUpdate) Mutation() *CallingPointMutation {
	return cpu.mutation
}

// ClearPlatform clears the "platform" edge to the Platform entity.
func (cpu *CallingPointUpdate) ClearPlatform() *CallingPointUpdate {
	cpu.mutation.ClearPlatform()
	return cpu
}

// ClearService clears the "service" edge to the Service entity.
func (cpu *CallingPointUpdate) ClearService() *CallingPointUpdate {
	cpu.mutation.ClearService()
	return cpu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cpu *CallingPointUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cpu.hooks) == 0 {
		affected, err = cpu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CallingPointMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cpu.mutation = mutation
			affected, err = cpu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cpu.hooks) - 1; i >= 0; i-- {
			if cpu.hooks[i] == nil {
				return 0, fmt.Errorf("entities: uninitialized hook (forgotten import entities/runtime?)")
			}
			mut = cpu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cpu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cpu *CallingPointUpdate) SaveX(ctx context.Context) int {
	affected, err := cpu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cpu *CallingPointUpdate) Exec(ctx context.Context) error {
	_, err := cpu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cpu *CallingPointUpdate) ExecX(ctx context.Context) {
	if err := cpu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cpu *CallingPointUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   callingpoint.Table,
			Columns: callingpoint.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: callingpoint.FieldID,
			},
		},
	}
	if ps := cpu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cpu.mutation.ArrivalTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: callingpoint.FieldArrivalTime,
		})
	}
	if value, ok := cpu.mutation.DepartureTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: callingpoint.FieldDepartureTime,
		})
	}
	if cpu.mutation.PlatformCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   callingpoint.PlatformTable,
			Columns: []string{callingpoint.PlatformColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: platform.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cpu.mutation.PlatformIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   callingpoint.PlatformTable,
			Columns: []string{callingpoint.PlatformColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: platform.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cpu.mutation.ServiceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   callingpoint.ServiceTable,
			Columns: []string{callingpoint.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: service.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cpu.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   callingpoint.ServiceTable,
			Columns: []string{callingpoint.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: service.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cpu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{callingpoint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// CallingPointUpdateOne is the builder for updating a single CallingPoint entity.
type CallingPointUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CallingPointMutation
}

// SetArrivalTime sets the "arrival_time" field.
func (cpuo *CallingPointUpdateOne) SetArrivalTime(t time.Time) *CallingPointUpdateOne {
	cpuo.mutation.SetArrivalTime(t)
	return cpuo
}

// SetNillableArrivalTime sets the "arrival_time" field if the given value is not nil.
func (cpuo *CallingPointUpdateOne) SetNillableArrivalTime(t *time.Time) *CallingPointUpdateOne {
	if t != nil {
		cpuo.SetArrivalTime(*t)
	}
	return cpuo
}

// SetDepartureTime sets the "departure_time" field.
func (cpuo *CallingPointUpdateOne) SetDepartureTime(t time.Time) *CallingPointUpdateOne {
	cpuo.mutation.SetDepartureTime(t)
	return cpuo
}

// SetNillableDepartureTime sets the "departure_time" field if the given value is not nil.
func (cpuo *CallingPointUpdateOne) SetNillableDepartureTime(t *time.Time) *CallingPointUpdateOne {
	if t != nil {
		cpuo.SetDepartureTime(*t)
	}
	return cpuo
}

// SetPlatformID sets the "platform" edge to the Platform entity by ID.
func (cpuo *CallingPointUpdateOne) SetPlatformID(id int) *CallingPointUpdateOne {
	cpuo.mutation.SetPlatformID(id)
	return cpuo
}

// SetNillablePlatformID sets the "platform" edge to the Platform entity by ID if the given value is not nil.
func (cpuo *CallingPointUpdateOne) SetNillablePlatformID(id *int) *CallingPointUpdateOne {
	if id != nil {
		cpuo = cpuo.SetPlatformID(*id)
	}
	return cpuo
}

// SetPlatform sets the "platform" edge to the Platform entity.
func (cpuo *CallingPointUpdateOne) SetPlatform(p *Platform) *CallingPointUpdateOne {
	return cpuo.SetPlatformID(p.ID)
}

// SetServiceID sets the "service" edge to the Service entity by ID.
func (cpuo *CallingPointUpdateOne) SetServiceID(id int) *CallingPointUpdateOne {
	cpuo.mutation.SetServiceID(id)
	return cpuo
}

// SetNillableServiceID sets the "service" edge to the Service entity by ID if the given value is not nil.
func (cpuo *CallingPointUpdateOne) SetNillableServiceID(id *int) *CallingPointUpdateOne {
	if id != nil {
		cpuo = cpuo.SetServiceID(*id)
	}
	return cpuo
}

// SetService sets the "service" edge to the Service entity.
func (cpuo *CallingPointUpdateOne) SetService(s *Service) *CallingPointUpdateOne {
	return cpuo.SetServiceID(s.ID)
}

// Mutation returns the CallingPointMutation object of the builder.
func (cpuo *CallingPointUpdateOne) Mutation() *CallingPointMutation {
	return cpuo.mutation
}

// ClearPlatform clears the "platform" edge to the Platform entity.
func (cpuo *CallingPointUpdateOne) ClearPlatform() *CallingPointUpdateOne {
	cpuo.mutation.ClearPlatform()
	return cpuo
}

// ClearService clears the "service" edge to the Service entity.
func (cpuo *CallingPointUpdateOne) ClearService() *CallingPointUpdateOne {
	cpuo.mutation.ClearService()
	return cpuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cpuo *CallingPointUpdateOne) Select(field string, fields ...string) *CallingPointUpdateOne {
	cpuo.fields = append([]string{field}, fields...)
	return cpuo
}

// Save executes the query and returns the updated CallingPoint entity.
func (cpuo *CallingPointUpdateOne) Save(ctx context.Context) (*CallingPoint, error) {
	var (
		err  error
		node *CallingPoint
	)
	if len(cpuo.hooks) == 0 {
		node, err = cpuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CallingPointMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cpuo.mutation = mutation
			node, err = cpuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cpuo.hooks) - 1; i >= 0; i-- {
			if cpuo.hooks[i] == nil {
				return nil, fmt.Errorf("entities: uninitialized hook (forgotten import entities/runtime?)")
			}
			mut = cpuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cpuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cpuo *CallingPointUpdateOne) SaveX(ctx context.Context) *CallingPoint {
	node, err := cpuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cpuo *CallingPointUpdateOne) Exec(ctx context.Context) error {
	_, err := cpuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cpuo *CallingPointUpdateOne) ExecX(ctx context.Context) {
	if err := cpuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cpuo *CallingPointUpdateOne) sqlSave(ctx context.Context) (_node *CallingPoint, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   callingpoint.Table,
			Columns: callingpoint.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: callingpoint.FieldID,
			},
		},
	}
	id, ok := cpuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`entities: missing "CallingPoint.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cpuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, callingpoint.FieldID)
		for _, f := range fields {
			if !callingpoint.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("entities: invalid field %q for query", f)}
			}
			if f != callingpoint.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cpuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cpuo.mutation.ArrivalTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: callingpoint.FieldArrivalTime,
		})
	}
	if value, ok := cpuo.mutation.DepartureTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: callingpoint.FieldDepartureTime,
		})
	}
	if cpuo.mutation.PlatformCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   callingpoint.PlatformTable,
			Columns: []string{callingpoint.PlatformColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: platform.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cpuo.mutation.PlatformIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   callingpoint.PlatformTable,
			Columns: []string{callingpoint.PlatformColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: platform.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cpuo.mutation.ServiceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   callingpoint.ServiceTable,
			Columns: []string{callingpoint.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: service.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cpuo.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   callingpoint.ServiceTable,
			Columns: []string{callingpoint.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: service.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CallingPoint{config: cpuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cpuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{callingpoint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
