// Code generated by entc, DO NOT EDIT.

package entities

import (
	"fmt"
	"strings"
	"time"

	"bitbucket.org/sea_wolf/departure_board-go/v2/entities/callingpoint"
	"bitbucket.org/sea_wolf/departure_board-go/v2/entities/platform"
	"entgo.io/ent/dialect/sql"
)

// CallingPoint is the model entity for the CallingPoint schema.
type CallingPoint struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ArrivalTime holds the value of the "arrival_time" field.
	ArrivalTime time.Time `json:"arrival_time,omitempty"`
	// DepartureTime holds the value of the "departure_time" field.
	DepartureTime time.Time `json:"departure_time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CallingPointQuery when eager-loading is set.
	Edges                   CallingPointEdges `json:"edges"`
	platform_calling_points *int
}

// CallingPointEdges holds the relations/edges for other nodes in the graph.
type CallingPointEdges struct {
	// Platform holds the value of the platform edge.
	Platform *Platform `json:"platform,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PlatformOrErr returns the Platform value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CallingPointEdges) PlatformOrErr() (*Platform, error) {
	if e.loadedTypes[0] {
		if e.Platform == nil {
			// The edge platform was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: platform.Label}
		}
		return e.Platform, nil
	}
	return nil, &NotLoadedError{edge: "platform"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CallingPoint) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case callingpoint.FieldID:
			values[i] = new(sql.NullInt64)
		case callingpoint.FieldArrivalTime, callingpoint.FieldDepartureTime:
			values[i] = new(sql.NullTime)
		case callingpoint.ForeignKeys[0]: // platform_calling_points
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type CallingPoint", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CallingPoint fields.
func (cp *CallingPoint) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case callingpoint.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			cp.ID = int(value.Int64)
		case callingpoint.FieldArrivalTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field arrival_time", values[i])
			} else if value.Valid {
				cp.ArrivalTime = value.Time
			}
		case callingpoint.FieldDepartureTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field departure_time", values[i])
			} else if value.Valid {
				cp.DepartureTime = value.Time
			}
		case callingpoint.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field platform_calling_points", value)
			} else if value.Valid {
				cp.platform_calling_points = new(int)
				*cp.platform_calling_points = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryPlatform queries the "platform" edge of the CallingPoint entity.
func (cp *CallingPoint) QueryPlatform() *PlatformQuery {
	return (&CallingPointClient{config: cp.config}).QueryPlatform(cp)
}

// Update returns a builder for updating this CallingPoint.
// Note that you need to call CallingPoint.Unwrap() before calling this method if this CallingPoint
// was returned from a transaction, and the transaction was committed or rolled back.
func (cp *CallingPoint) Update() *CallingPointUpdateOne {
	return (&CallingPointClient{config: cp.config}).UpdateOne(cp)
}

// Unwrap unwraps the CallingPoint entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cp *CallingPoint) Unwrap() *CallingPoint {
	tx, ok := cp.config.driver.(*txDriver)
	if !ok {
		panic("entities: CallingPoint is not a transactional entity")
	}
	cp.config.driver = tx.drv
	return cp
}

// String implements the fmt.Stringer.
func (cp *CallingPoint) String() string {
	var builder strings.Builder
	builder.WriteString("CallingPoint(")
	builder.WriteString(fmt.Sprintf("id=%v", cp.ID))
	builder.WriteString(", arrival_time=")
	builder.WriteString(cp.ArrivalTime.Format(time.ANSIC))
	builder.WriteString(", departure_time=")
	builder.WriteString(cp.DepartureTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CallingPoints is a parsable slice of CallingPoint.
type CallingPoints []*CallingPoint

func (cp CallingPoints) config(cfg config) {
	for _i := range cp {
		cp[_i].config = cfg
	}
}
