// Code generated by entc, DO NOT EDIT.

package entities

import (
	"fmt"
	"strings"
	"time"

	"bitbucket.org/sea_wolf/departure_board-go/v2/entities/day"
	"entgo.io/ent/dialect/sql"
)

// Day is the model entity for the Day schema.
type Day struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Date holds the value of the "date" field.
	Date time.Time `json:"date,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DayQuery when eager-loading is set.
	Edges DayEdges `json:"edges"`
}

// DayEdges holds the relations/edges for other nodes in the graph.
type DayEdges struct {
	// Services holds the value of the services edge.
	Services []*Service `json:"services,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ServicesOrErr returns the Services value or an error if the edge
// was not loaded in eager-loading.
func (e DayEdges) ServicesOrErr() ([]*Service, error) {
	if e.loadedTypes[0] {
		return e.Services, nil
	}
	return nil, &NotLoadedError{edge: "services"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Day) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case day.FieldID:
			values[i] = new(sql.NullInt64)
		case day.FieldDate:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Day", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Day fields.
func (d *Day) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case day.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			d.ID = int(value.Int64)
		case day.FieldDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date", values[i])
			} else if value.Valid {
				d.Date = value.Time
			}
		}
	}
	return nil
}

// QueryServices queries the "services" edge of the Day entity.
func (d *Day) QueryServices() *ServiceQuery {
	return (&DayClient{config: d.config}).QueryServices(d)
}

// Update returns a builder for updating this Day.
// Note that you need to call Day.Unwrap() before calling this method if this Day
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Day) Update() *DayUpdateOne {
	return (&DayClient{config: d.config}).UpdateOne(d)
}

// Unwrap unwraps the Day entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (d *Day) Unwrap() *Day {
	tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("entities: Day is not a transactional entity")
	}
	d.config.driver = tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Day) String() string {
	var builder strings.Builder
	builder.WriteString("Day(")
	builder.WriteString(fmt.Sprintf("id=%v", d.ID))
	builder.WriteString(", date=")
	builder.WriteString(d.Date.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Days is a parsable slice of Day.
type Days []*Day

func (d Days) config(cfg config) {
	for _i := range d {
		d[_i].config = cfg
	}
}
