// Code generated by entc, DO NOT EDIT.

package station

import (
	"bitbucket.org/sea_wolf/departure_board-go/v2/entities/predicate"
	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// Crs applies equality check predicate on the "crs" field. It's identical to CrsEQ.
func Crs(v string) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCrs), v))
	})
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldName), v))
	})
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldName), v))
	})
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Station {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Station(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldName), v...))
	})
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Station {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Station(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldName), v...))
	})
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldName), v))
	})
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldName), v))
	})
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldName), v))
	})
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldName), v))
	})
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldName), v))
	})
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldName), v))
	})
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldName), v))
	})
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldName), v))
	})
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldName), v))
	})
}

// CrsEQ applies the EQ predicate on the "crs" field.
func CrsEQ(v string) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCrs), v))
	})
}

// CrsNEQ applies the NEQ predicate on the "crs" field.
func CrsNEQ(v string) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCrs), v))
	})
}

// CrsIn applies the In predicate on the "crs" field.
func CrsIn(vs ...string) predicate.Station {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Station(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCrs), v...))
	})
}

// CrsNotIn applies the NotIn predicate on the "crs" field.
func CrsNotIn(vs ...string) predicate.Station {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Station(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCrs), v...))
	})
}

// CrsGT applies the GT predicate on the "crs" field.
func CrsGT(v string) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCrs), v))
	})
}

// CrsGTE applies the GTE predicate on the "crs" field.
func CrsGTE(v string) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCrs), v))
	})
}

// CrsLT applies the LT predicate on the "crs" field.
func CrsLT(v string) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCrs), v))
	})
}

// CrsLTE applies the LTE predicate on the "crs" field.
func CrsLTE(v string) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCrs), v))
	})
}

// CrsContains applies the Contains predicate on the "crs" field.
func CrsContains(v string) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldCrs), v))
	})
}

// CrsHasPrefix applies the HasPrefix predicate on the "crs" field.
func CrsHasPrefix(v string) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldCrs), v))
	})
}

// CrsHasSuffix applies the HasSuffix predicate on the "crs" field.
func CrsHasSuffix(v string) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldCrs), v))
	})
}

// CrsEqualFold applies the EqualFold predicate on the "crs" field.
func CrsEqualFold(v string) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldCrs), v))
	})
}

// CrsContainsFold applies the ContainsFold predicate on the "crs" field.
func CrsContainsFold(v string) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldCrs), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Station) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Station) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Station) predicate.Station {
	return predicate.Station(func(s *sql.Selector) {
		p(s.Not())
	})
}
