// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CallingPoint is the predicate function for callingpoint builders.
type CallingPoint func(*sql.Selector)

// Day is the predicate function for day builders.
type Day func(*sql.Selector)

// Platform is the predicate function for platform builders.
type Platform func(*sql.Selector)

// Service is the predicate function for service builders.
type Service func(*sql.Selector)

// Station is the predicate function for station builders.
type Station func(*sql.Selector)

// TOC is the predicate function for toc builders.
type TOC func(*sql.Selector)
